import '@/styles/globals.css'
import { Roboto } from 'next/font/google'
import type { Metadata } from 'next'
import { Header } from '@/ui/Header'
import { Footer } from '@/ui/Footer'

const roboto = Roboto({ variable: '--font-roboto', subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='es'>
			<body className={`${roboto.variable}`}>
				<div className='site-container'>{children}</div>
			</body>
		</html>
	)
}
